generator:
  class:              sfDoctrineAdminGenerator
  param:
    model_class:      sfGuardPermission
    theme:            default

    list:
      title:          Permission list
      display:        [=name, description]

    edit:
      title:          Edit permission
