generator:
  class:              sfDoctrineAdminGenerator
  param:
    model_class:      sfGuardGroup
    theme:            default

    list:
      title:          Group list
      display:        [=name, description]

    edit:
      title:          Edit "%%name%%" group
      fields:
        permissions:  { type: doctrine_admin_check_list, params: through_class=sfGuardGroupPermission }
      display:        [ name, description, permissions ]
