sfGuardGroup:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
    description: string(1000)
  relations:
    Users:
      class: sfGuardUser
      refClass: sfGuardUserGroup
      local: group_id
      foreign: user_id
      foreignAlias: Groups
    Permissions:
      class: sfGuardPermission
      local: group_id
      foreign: permission_id
      refClass: sfGuardGroupPermission
      foreignAlias: Groups

sfGuardPermission:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
    description: string(1000)

sfGuardGroupPermission:
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer(4)
      primary: true
    permission_id:
      type: integer(4)
      primary: true
  relations:
    Group:
      local: group_id
      class: sfGuardGroup
      foreignType: one
      onDelete: CASCADE
    Permission:
      local: permission_id
      class: sfGuardPermission
      foreignType: one
      onDelete: CASCADE

sfGuardUser:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    username: string(128)
    algorithm:
      type: string(128)
      unique: true
    salt: string(128)
    password: string(128)
    is_active:
      type: boolean
      default: 1
    is_super_admin:
      type: boolean
      default: 0
    last_login:
      type: timestamp
  relations:
    Groups:
      class: sfGuardGroup
      local: user_id
      foreign: group_id
      refClass: sfGuardUserGroup
      foreignAlias: Users
    Permissions:
      class: sfGuardPermission
      local: user_id
      foreign: permission_id
      refClass: sfGuardUserPermission
      foreignAlias: Users

sfGuardUserPermission:
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer(4)
      primary: true
    permission_id:
      type: integer(4)
      primary: true
  relations:
    User:
      local: user_id
      class: sfGuardUser
      foreignType: one
      onDelete: CASCADE
    Permission:
      local: permission_id
      class: sfGuardPermission
      foreignType: one
      onDelete: CASCADE

sfGuardUserGroup:
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer(4)
      primary: true
    group_id:
      type: integer(4)
      primary: true
  relations:
    User:
      local: user_id
      class: sfGuardUser
      foreignType: one
      onDelete: CASCADE
    Group:
      local: group_id
      class: sfGuardGroup
      foreignType: one
      onDelete: CASCADE

sfGuardRememberKey:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
    remember_key: string(32)
    ip_address:
      type: string(15)
      primary: true
  relations:
    User:
      local: user_id
      class: sfGuardUser
      foreignAlias: RememberKeys
      foreignType: one
      onDelete: CASCADE